[phases.setup]
nixPkgs = ["php85", "php85Extensions.pdo", "php85Extensions.sqlite3", "php85WithExtensions", ""php85Extensions.pdo_pgsql", "php85Extensions.pgsql", "php85Extensions.mbstring", "php85Extensions.xml", "php85Extensions.tokenizer", "php85Extensions.openssl", "php85Extensions.curl", "php85Extensions.fileinfo", "nodejs", "nodePackages.npm"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php artisan config:clear && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
